[package]
edition = "2018"
name = "metapool"
version = "1.2.1"
authors = ["Metapool.app <hello@metapool.app>"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.1.0"
near-contract-standards = "3.1.0"
uint = { version = "0.9.5", default-features = false }

